- name: Install required system packages
  apt-get:
    pkg:
      - nginx
      - openssl
  tags:
    - install

- name: Install letsencrypt certbot repo
  apt_repository:
    repo: ppa:certbot/certbot
  when: clojure_uberjar_webapp_nginx_use_ssl|bool
  tags:
    - install

- name: Install letsencrypt certbot
  apt-get:
    pkg:
      - python-certbot-nginx
  when: clojure_uberjar_webapp_nginx_use_ssl|bool
  tags:
    - install
    
- name: Disable default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  tags:
    - install
    
- name: nginx base config
  copy: src=files/nginx.conf dest="{{ clojure_uberjar_webapp_nginx_dir }}/nginx.conf"
  notify:
    - reload nginx
  tags:
    - configure
    
- name: nginx app config
  template:
    src: "templates/app-nginx.conf.j2"
    dest: "{{ clojure_uberjar_webapp_nginx_sites_available }}"
  # when: not (clojure_uberjar_webapp_nginx_use_ssl)
  tags:
    - configure
  notify:
    - "nginx config changed"

- name: nginx link app config
  file: src="{{ clojure_uberjar_webapp_nginx_sites_available }}" dest="{{ clojure_uberjar_webapp_nginx_sites_enabled }}" state=link
  tags:
    - configure
